### ISSUE TITLE
Wiki table problem

### ISSUE THREAD

**Issue by hacetin** [mmattioli/ZedBoard-OLED#1]
Thanks for your codes, it helped me a lot. But, I guess, there is a mistake in the table which you explain how the bits correspond to individual pixels used to depict the ASCII character H on the display. You should delete one of second, third and fourth row.

**Comment by mmattioli** [comment]
Glad it helped! Could you explain a little further? I'm not entirely sure where the mistake is?

**Comment by mmattioli** [comment]
Closing this for lack of clarification. Feel free to comment if you can provide further clarification. Thanks.
